export const INIT_USERS = "INIT_USERS"
export const INIT_CATS = "INIT_CATS"
export const INIT_BLOGS = "INIT_BLOGS"
export const SET_CAT = "SET_CAT"
export const SET_LOGIN= "SET_LOGIN"
export const ADD_BLOG = "ADD_BLOG"
export const ADD_CAT= "ADD_CAT"